{
  mockRetryProviderPlugin.setAborted(false).setNextRetryDate(new DateTime().plusDays(1));
  mockRetryAuthorizeOperationCallback.setResult(null).setException(new PaymentApiException(ErrorCode.__UNKNOWN_ERROR_CODE,"bla"));
  runner.setOperationCallback(mockRetryAuthorizeOperationCallback).setContext(paymentStateContext);
  final State state=retrySMHelper.getRetriedState();
  final UUID transactionId=UUID.randomUUID();
  paymentDao.insertPaymentAttemptWithProperties(new PaymentAttemptModelDao(account.getId(),paymentMethodId,utcNow,utcNow,paymentExternalKey,transactionId,paymentTransactionExternalKey,TransactionType.AUTHORIZE,state.getName(),amount,currency,null,EMPTY_PROPERTIES),internalCallContext);
  try {
    runner.run(state,false,TransactionType.AUTHORIZE,account,paymentMethodId,null,paymentExternalKey,paymentTransactionExternalKey,amount,currency,emptyProperties,null,callContext,internalCallContext);
    fail("Expecting paymentApiException...");
  }
 catch (  final PaymentApiException e) {
    final PaymentAttemptModelDao pa=paymentDao.getPaymentAttemptByTransactionExternalKey(paymentTransactionExternalKey,internalCallContext).get(0);
    assertEquals(pa.getTransactionExternalKey(),paymentTransactionExternalKey);
    assertEquals(pa.getStateName(),"RETRIED");
    assertEquals(pa.getTransactionType(),TransactionType.AUTHORIZE);
  }
}
