{
  int retry=1;
  Exception lastException=null;
  do {
    try {
      return task.call();
    }
 catch (    Exception e) {
      lastException=e;
    }
  }
 while (retry-- > 0);
  throw lastException;
}
